#!/bin/bash

rm ~/.tmux.conf
ln -s ~/.dotfiles/tmux/.tmux.conf ~/.tmux.conf

rm ~/.zshrc
ln -s ~/.dotfiles/zsh/.zshrc ~/.zshrc

rm -rf ~/.oh-my-zsh/custom
ln -s ~/.dotfiles/zsh/custom ~/.oh-my-zsh/custom

rm -rf ~/.config/nvim
ln -s ~/.dotfiles/nvim/nvim ~/.config/nvim

